### ISSUE TITLE
DOESN'T WORK ANYMORE

### ISSUE THREAD

**Issue by tomkenner** [fewieden/MMM-WienerLinien#19]
Since a few days the module doesn't work anymore. It show "lade..." but no informations.

**Comment by fewieden** [comment]
@tomkenner do you see any errors in the electron or terminal logs?

**Comment by tomkenner** [comment]
In the .pm2/logs/mm-out.log I get:

[22.01.2022 17:02.20.435] [LOG]   Error getting WienerLinien station data: FetchError: request to https://www.wienerlinien.at/ogd_realtime/monitor?rbl=1293&rbl=2983 failed, reason: connect ETIMEDOUT 193.178.171.28:443
    at ClientRequest.<anonymous> (/home/pi/MagicMirror/modules/MMM-WienerLinien/node_modules/node-fetch/lib/index.js:1483:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

**Comment by fewieden** [comment]
@tomkenner I just tested the module for your other issue and I received the data.

The error is indicating that the API requests are timing out. Does any other of your modules use an active internet connection and update the data correctly?

**Comment by tomkenner** [comment]
Yes, the internet connection is working for the other modules (weather, news feed, Google Slides)

**Comment by fewieden** [comment]
@tomkenner I can't reproduce your issues. If you are interested I can offer a remote debugging session. Just connect with me on the MagicMirror discord channel.

**Comment by Krashdeez** [comment]
Hello, 

I also get the same "error" I have a new installation and I also only get "loading" more does not come.
Any Ideas what can i Do ? 

Without any modifications

Many thanks

**Comment by Krashdeez** [comment]
ok...

I have found a solution, but restarting the server every time a change is tedious...

**Comment by Krashdeez** [comment]
ok, 

now i get 

[18.02.2022 00:36.45.499] [LOG] Error getting WienerLinien station data: TypeError: Cannot read property 'toString' of null

**Comment by fewieden** [comment]
@Krashdeez looks like the module has an issue to parse the departure times.

Can you please share your config options for the module?

**Comment by Knapoc** [comment]
@fewieden I'm experiencing the same parsing error:

```
mm  | Error getting WienerLinien station data: TypeError: Cannot read properties of null (reading 'toString')
0|mm  |     at Class.handleData (/home/pi/MagicMirror/modules/MMM-WienerLinien/node_helper.js:197:102)
0|mm  |     at Class.getMonitoringData (/home/pi/MagicMirror/modules/MMM-WienerLinien/node_helper.js:90:22)
0|mm  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|mm  |     at Class.getData (/home/pi/MagicMirror/modules/MMM-WienerLinien/node_helper.js:61:9)
0|mm  |     at Timeout._onTimeout (/home/pi/MagicMirror/modules/MMM-WienerLinien/node_helper.js:48:17)
0|mm  | [03.07.2022 20:54.16.584] [LOG]   
0|mm  | Error getting WienerLinien station data: TypeError: Cannot read properties of null (reading 'toString')
0|mm  |     at Class.handleData (/home/pi/MagicMirror/modules/MMM-WienerLinien/node_helper.js:197:102)
0|mm  |     at Class.getMonitoringData (/home/pi/MagicMirror/modules/MMM-WienerLinien/node_helper.js:90:22)
0|mm  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|mm  |     at Class.getData (/home/pi/MagicMirror/modules/MMM-WienerLinien/node_helper.js:61:9)
0|mm  |     at Timeout._onTimeout (/home/pi/MagicMirror/modules/MMM-WienerLinien/node_helper.js:48:17)
```

For my config station `4115` is to blame since it serves an empty response under departure_time:
https://www.wienerlinien.at/ogd_realtime/monitor?stopId=4115

Maybe it make sense to handle empty responses in a more graceful way.

**Comment by fewieden** [comment]
@Knapoc I was able to reproduce the issue yesterday before work.

When I tried to debug in the evening the module worked as expected again, looks like the station had a temporary problem for a couple of days.

Do you know if the station or the line U1 were maybe not operating during the last days, e.g. due to construction?

![image](https://user-images.githubusercontent.com/9334168/177706751-79a1fb56-359d-4dc5-ac87-736c3527d820.png)

**Comment by Knapoc** [comment]
@fewieden afaik the station was operating normally. The api calls for this line and station in the other direction were also working. 

But in general it seems that for some stations out of operation the api calls are still successful, for others not (check U2 station which are currently out of operation: Rathaus to Karlsplatz). 

Imho the module should still show results for successful api calls. Unfortunately I doubt that I have the required knowledge to implement this. Maybe I’ll dig into it when I find some time.

**Comment by fewieden** [comment]
@Knapoc I can add a safeguard for that specific line. However, the problem is, that I don't have the exact server response saved, in order to figure out if we can retrieve the times in a different way.

Usually, the module tries to get the departure times. When the station doesn't provide those, which happened for a lot of metro stops when developing the module initially, I saw that there can be a workaround to retrieve the times through other means. In this case, this fallback failed.

By adding a safeguard to not break the code but not adding another fallback the result would be an empty schedule.

I can see if I will find some more information in the API docs the next time I have time to work on the module.

**Comment by VincenzoKoestler** [comment]
```
Error getting WienerLinien station data: TypeError: Cannot read property 'toString' of null
at Class.handleData (/home/pi/MagicMirror/modules/MMM-WienerLinien/node_helper.js:197:102)
at Class.getMonitoringData (/home/pi/MagicMirror/modules/MMM-WienerLinien/node_helper.js:90:22)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Class.getData (/home/pi/MagicMirror/modules/MMM-WienerLinien/node_helper.js:61:9)
```
@fewieden also experiencing this issue
I tried with different stations that where serving proper departure-time responses (at least I think so?)
dont really know why its happening

```
{"data":{"monitors":[{"locationStop":{"type":"Feature","geometry":{"type":"Point","coordinates":[16.3597025,48.1966775]},"properties":{"name":"60200670","title":"Kettenbrückengasse","municipality":"Wien","municipalityId":90001,"type":"stop","coordName":"WGS84","attributes":{"rbl":5570}}},"lines":[{"name":"N60","towards":"Ring, Kai","direction":"R","platform":"2","richtungsId":"2","barrierFree":true,"realtimeSupported":true,"trafficjam":false,"departures":{"departure":[{"departureTime":{"timePlanned":"2022-08-04T02:21:30.000+0200","timeReal":"2022-08-04T02:24:07.000+0200","countdown":1}},{"departureTime":{"timePlanned":"2022-08-04T02:51:30.000+0200","timeReal":"2022-08-04T02:51:30.000+0200","countdown":28}},{"departureTime":{"timePlanned":"2022-08-04T03:21:30.000+0200","timeReal":"2022-08-04T03:21:30.000+0200","countdown":58}}]},"type":"ptBusNight","lineId":560}],"attributes":{}}]},"message":{"value":"OK","messageCode":1,"serverTime":"2022-08-04T02:22:40.000+0200"}}
```
Thats the response from the source
